require 'dotenv'
Dotenv.load

default_platform :ios

platform :ios do

  lane :test do
    fastlane_require 'dotenv'
    xcbuild(
      workspace: "#{ENV['PROJECT_NAME']}.xcworkspace",
      scheme: ENV['SCHEME_NAME'],
      device: "iPhone 7",
    )
  end
end
